**Added:** None

**Changed:** None

**Deprecated:** None

**Removed:** None

**Fixed:**

* Jupyter kernel was no longer properly running subprocess commands.
  This has been fixed.

**Security:** None
